export const ACTIONS = {
    FETCH_ALL_BOOKMARKS: 'FETCH_ALL_BOOKMARKS',
    FETCH_SINGLE_BOOKMARK_REQUEST: 'FETCH_SINGLE_BOOKMARK_REQUEST',
    FETCH_SINGLE_BOOKMARK_SUCCESS: 'FETCH_SINGLE_BOOKMARK_SUCCESS',
    FETCH_SINGLE_BOOKMARK_ERROR: 'FETCH_SINGLE_BOOKMARK_ERROR',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    DELETE_BOOKMARK: 'DELETE_BOOKMARK',
};